JeffersonLab/clas12-validation

.github/workflows/ci.yml
This is so that we don't have to set every matrix element as a required status check.
This new job may be extended to do artifact collection, summaries, deployment, etc.
=> ci: add single final job that can be required for status checks

config/evgen_ci.json
The CI is getting slow, because there are too many matrix elements trying to run simultaneously. For now, to speed up development, restrict to 1 event generation type.
We can revert this PR later, when we want to run this workflow for real.
=> ci: temporarily restrict to a single event generation type

.github/workflows/ci.yml
Triggering workflows may send `num_events: 0` in the dispatch payload, which will then use the default value set here (`env.num_events`).
=> feat: allow triggerers to not need a default `num_events`

.github/workflows/ci.yml
Use the actual repo name instead of some shorter name, or in lower case. This will allow the dispatch triggering workflow to set the payload repo name of the caller.
=> refactor: use upstream repository name in variables

.github/workflows/ci.yml
Allow the caller to have full control of the concurrency class.
=> fix: do not set concurrency class to avoid conflict with that of callers

.github/workflows/ci.yml, bin/multiplicity.groovy
Instead of using both `evgen` and `config` names.
=> fix: use `evgen` name to set the particle bank for multiplicity analysis

.github/workflows/ci.yml
=> style: use `description` nodes for workflow inputs

.github/workflows/ci.yml
Adds the triggering event to the summary table, so that scheduled runs are not confused by PR triggers.
=> fix: clarify scheduled runs in summary

.github/workflows/ci.yml
We are often getting 404 errors on `download-artifact` steps, *e.g.*:
```
2023-11-26T08:41:38.6458962Z ##[error]Unable to download the artifact: Error: Unexpected http 404 during download for https://pipelinesghubeus8.actions.githubusercontent.com/7JZzylYNHFlQVRIL4OpYRCpWaXIHGbvCjY4Iet1QKs3KlDPhvh/_apis/resources/Containers/3284543?itemPath=build%2Fclas12Tags.tar.gz
```
This PR should help mitigate.
=> fix: retry `download-artifact` steps when they 404

LICENSE
- chose MIT license to keep it simple and since many GitHub actions use this license (this repository isn't really an action, but it's primarily a reusable workflow)
- copyright owner set to "Jefferson Lab and contributors"
- this does not retroactively apply to [v0.1](https://github.com/JeffersonLab/clas12-validation/releases/tag/v0.1)
- the current version on `main` is completely separate from v0.1 and @c-dilks is currently the only contributor
- FYI @tylern4 and @naharrison, who wrote v0.1
=> fix: add MIT license

.github/workflows/ci.yml
This'll allow us to `checkout` any historical `ref` (by commit hash, branch name, tag, etc.)
=> fix: allow historical `ref`s in `checkout` steps

.github/workflows/ci.yml
If it takes a while for a matrix job step to fail, and if the matrix is large, it will take very long for the workflow to report failure, since all jobs will be attempted and there is a limit to the number of parallel-running jobs. This enables `fail-fast` for all job matrices, so that the maximum workflow run time is closer to the maximum allowed job run time.
=> ci: always `fail-fast`

.github/workflows/ci.yml, bin/ci_build_gemc.sh
GitHub hosted runners have been [upgraded from 2-vCPU to 4-vCPU](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/), so let's make use of the extra power.
=> ci: build with 4 threads, since runners have been upgraded

.github/workflows/ci.yml
[`wretry.action`](https://github.com/Wandalen/wretry.action) is a very useful action for automatically retrying steps, which helped us resolve an issue here where `artifact-download` was sporadically failing. Unfortunately I'm not sure how to get it to work with `v4` artifact actions syntax, which requires `pattern:` and `match-multiple:` keys.
For now, let's try to run without `wretry.action` and see if the `v4` artifact actions are more stable nowadays.
=> ci: remove `Wandalen/wretry.action`

.github/workflows/ci.yml, README.md
The GitHub `checkout` action accepts general `ref`s, not just branches. To be more clear, we rename the corresponding variables.
> [!WARNING]
> This is a breaking change to all caller workflows that specify this variable
> - [ ] update `coatjava` (the only caller that needs to respect this PR)
=> style!: rename input `git_upstream` key `branch`->`ref`

.github/workflows/ci.yml
We've been experiencing sporadic `coatjava` build failures, usually from maven repo connection issues, such as timeouts. Example:
```
2024-02-05T09:06:44.9775242Z [ERROR] Failed to execute goal on project clas12rec: Could not resolve dependencies for project org.jlab.clas:clas12rec:pom:10.0.6-SNAPSHOT: Failed to collect dependencies at org.jlab:groot:jar:4.0.5 -> org.freehep:freehep-jminuit:jar:1.0.2: Failed to read artifact descriptor for org.freehep:freehep-jminuit:jar:1.0.2: Could not transfer artifact org.freehep:freehep-jminuit:pom:1.0.2 from/to freehep-repo-public (https://srs.slac.stanford.edu/nexus/content/groups/freehep-maven2-public/): transfer failed for https://srs.slac.stanford.edu/nexus/content/groups/freehep-maven2-public/org/freehep/freehep-jminuit/1.0.2/freehep-jminuit-1.0 …
```
=> fix: use `wretry.action` for `build_coatjava`

.github/nightly-issue.md, .github/workflows/ci.yml, .github/workflows/schedule.yml
Fixes broken Validation callers, e.g. those from https://github.com/JeffersonLab/coatjava/pull/184 (@baltzell)
We only want `issue_bot` to run on `schedule` triggers, so move it to a dedicated workflow which calls the main `ci.yml` workflow, followed by `issue_bot`. This keeps the elevated permission requirement _out_ of the reusable workflow.
=> fix: move `issue_bot`, which requires elevated permissions, to separate workflow

.github/workflows/ci.yml
=> fix: lock `groovy` version to 4.0.3

.github/workflows/ci.yml, bin/ci_gemc_run.sh
@maureeungaro this PR will mean that validation tests will run with either:
- highest semver tag of `gemc`, if available in the container
- the default `gemc` version in the container, if highest semver is not available
(FYI @baltzell)
=> fix: if `module switch gemc/[highest-tag]` fails, just warn and proceed

bin/ci_gemc_run.sh
Only call `module switch gemc` if the pipeline built `gemc`, which should only happen from `clas12Tags` triggers. For all other triggers, _just_ use whatever `gemc` version in the container is.
=> fix: `module switch gemc` iff `gemc` was built

.github/workflows/ci.yml
requested by @maureeungaro 
---
close #103
close #104
close #105
close #106
=> ci(GEMC): use image `jeffersonlab/gemc:dev-g4v10.7.4-fedora36-cvmfs`

.github/workflows/ci.yml
blocker bug from 4.0.19 is resolved: https://issues.apache.org/jira/browse/GROOVY-11328
=> ci: revert to testing with latest groovy v4

.github/workflows/ci.yml
=> ci: change `gemc` docker image to tag `dev-fedora36`

.github/workflows/ci.yml, README.md, bin/ci_gemc_build.sh, bin/ci_gemc_run.sh
Closes #146 
The `dev` branches on `clas12Tags` and `clas12-config` have required some thought about choosing the correct versions of `gcards` and `gemc`. This PR:
- adds a table, showing what versions _should_ be used for each case
- handles `gemc` module switching more generally
=> ci: new scheme for handling GEMC and gcard versioning

.github/workflows/ci.yml
Adds input variable `gemc_image` to choose the Docker image for GEMC:
unfortunately we cannot simply pass the image name to the CI job step, so instead we have the following aliases:
- "fedora": docker://jeffersonlab/gemc:dev-fedora36
- "alma":   docker://jeffersonlab/gemc:dev-almalinux93
=> ci: allow for choice of GEMC image

.github/nightly-issue.md, .github/scheduled-issue.md, .github/workflows/schedule.yml
Nightly seems a bit too frequent, compared to the rate of change on our production branches; furthermore, when this high-statistics job is running, my (our?) other workflow runs on other `JeffersonLab`-owned repos are queued and have to wait for this one.
The new run times are Wednesday and Saturday at 03:30 EST / 04:30 EDT (=0830Z).
FYI @baltzell, @maureeungaro, @raffaelladevita
=> ci: scheduled tests are now twice per week instead of nightly

.github/workflows/ci.yml, .github/workflows/schedule.yml
- keep scheduled workflow's job matrix the same
- reduce default job matrix, which is triggered on PRs, pushes to `main`, and callers' default
=> ci: reduce default job matrix size

.github/workflows/ci.yml
=> ci: don't print download progress when building `coatjava`
