.gitignore, release-validation-1/gen.py, release-validation-1/run-clara-validate, release-validation-1/sim.py, release-validation-1/src/Makefile, release-validation-1/src/colors.hpp, release-validation-1/src/histogram.cpp, release-validation-1/src/histogram.hpp, release-validation-1/src/main.cpp, release-validation-1/src/main.hpp, release-validation-1/validate.sh
Also an addition of a validation program for momentum resolution.
=> Fixes to some scripts

.github/workflows/ci.yml
Fix the step list indentation; should not change anything.
=> style: step list indentation

.github/workflows/ci.yml
Apparently I am "manually running" everyone's workflow jobs, likely because I own the PAT. This PR adds the triggerer name to the action title, so it's clear who caused each dispatch.
=> feat: receive actor name from triggerer

.github/workflows/ci.yml, bin/multiplicity.groovy
Add particle multiplicity printout to the action summary, until we have some plotting tools.
This at least tests the reconstructed files to see what's inside.
=> feat: particle multiplicities

.github/workflows/ci.yml
Allow triggering workflows to set the number of events.
=> feat: add input for custom number of events

.github/workflows/ci.yml, bin/match_configs.rb, config/README.md, config/config_ci.json
Use a custom set of `clas12-config` files, requested by @raffaelladevita.
> The configurations that are significantly different are:
> - clas12-default
> - rga_spring2018
> - rga_fall2018
> - rgk_fall2018_FTOn
> - rgb_fall2019
> - rgc_summer2022_FTON
=> feat: use a custom set of `config` files

config/evgen_ci.json
=> ci: test larger set of event generation types

.github/workflows/ci.yml
cf. https://github.com/JeffersonLab/coatjava/pull/152
=> ci: do not `always()` run `final`

.github/workflows/ci.yml
Respect https://github.com/JeffersonLab/clas12-config/pull/31
=> feat: use list of config files specified in `clas12-config`

.github/workflows/ci.yml
=> fix: handle multi-line commit messages in summary

.github/workflows/ci.yml, bin/ci_build_gemc.sh
=> ci: use Zstandard compression

.github/workflows/ci.yml
Disable this workflow until further notice.
=> hotfix: disable the workflow

.github/workflows/ci.yml
=> ci: disable workflow with a dedicated step

bin/clas12-validation-notifier-bot.sh
Resolves #48 (as long as @baltzell uses this in a cronjob).
=> feat: get the status of the most recent scheduled workflow run

.github/workflows/ci.yml
Enforce a proper concurrency class
=> ci: enforce a concurrency class

.github/workflows/ci.yml
This allows one to run the validation workflow manually.
=> ci: add `workflow_dispatch` trigger

.github/workflows/ci.yml
Since it is not sanitized and therefore not safe
=> fix: don't read commit messages or PR titles

.github/workflows/ci.yml
note: see java21 project page: https://github.com/orgs/JeffersonLab/projects/45/views/1
=> ci: java 21

.github/workflows/ci.yml, bin/ci_gemc_run.sh, bin/multiplicity.groovy
runs `trutheff` from https://github.com/JeffersonLab/coatjava/pull/396
=> feat: report truth efficiency

.github/workflows/schedule.yml
- increase the frequency 2/week -> 3/week
- aligns better with typical business days
=> ci: change cron runs to Sun, Tue, Thu, at 0830Z

.github/workflows/ci.yml, bin/ci_gemc_run.sh
:warning: **breaking change** :warning: the meaning of workflow input `gemc_image` is changed: use the full URI, rather than a short name (`fedora` or `alma`)
- use sqlite file from cvmfs
- avoid too many connections to the mysql server
=> fix!: use CCDB sqlite URI

.github/workflows/ci.yml
see https://github.com/JeffersonLab/coatjava/pull/561
=> perf: use bigger heap size for `recon-util`

.github/workflows/ci.yml
- we are unable to run because of #187
- `wget` attempts from `build_coatjava` take almost 2 hours to fail, holding up CI queues
- for now, just fail `clas12-validation` jobs immediately
=> ci: fully disable

.github/workflows/ci.yml
This reverts commit ce42b87336652e2d87c0453c2674af2dc2c3c864.
=> ci: re-enable; reverts "ci: fully disable (#190)"
